name = "the-beyond"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
CF_ACCOUNT_ID = "049ff5e84ecf636b53b162cbb580aae6"

# Secrets (set via wrangler secret put):
# DEEPINFRA_TOKEN
# CF_TOKEN
