// Combined Pages Worker - handles /tick, /validate, /tts
// Generated by Mavis for ai-writings.pages.dev

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const path = url.pathname;
    
    // CORS headers
    const corsHeaders = {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type',
    };
    
    if (request.method === 'OPTIONS') {
      return new Response(null, { headers: corsHeaders });
    }
    
    if (path === '/tick' || path === '/api/tick') {
      const body = await request.json().catch(() => ({}));
      const ACCT_ID = '049ff5e84ecf636b53b162cbb580aae6';
      
      // Run 4 parallel upstream calls
      const [zaiRes, v4Res, qwenRes, fluxRes] = await Promise.allSettled([
        fetch('https://api.deepinfra.com/v1/openai/chat/completions', {
          method: 'POST',
          headers: { 'Authorization': `Bearer ${env.DEEPINFRA_TOKEN}`, 'Content-Type': 'application/json' },
          body: JSON.stringify({
            model: 'zai-org/GLM-5.3-Flash',
            messages: [{ role: 'user', content: body.prompt || 'What does the sailor see beyond the horizon?' }],
            max_tokens: 200, temperature: 0.9
          })
        }).then(r => r.json()).then(d => d?.choices?.[0]?.message?.content || 'silence').catch(() => 'silence'),
        
        fetch('https://api.deepinfra.com/v1/openai/chat/completions', {
          method: 'POST',
          headers: { 'Authorization': `Bearer ${env.DEEPINFRA_TOKEN}`, 'Content-Type': 'application/json' },
          body: JSON.stringify({
            model: 'deepseek-ai/DeepSeek-V4-Flash',
            messages: [{ role: 'user', content: 'Return ONLY JSON: {"compass":0.5,"depth":0.5,"clarity":0.5,"drift":0.5,"weight":0.5,"novel_dial":"silence"}' }],
            max_tokens: 200, temperature: 0.9
          })
        }).then(r => r.json()).then(d => d?.choices?.[0]?.message?.content || '{"compass":0.5}').catch(() => '{"compass":0.5}'),
        
        fetch('https://api.deepinfra.com/v1/openai/chat/completions', {
          method: 'POST',
          headers: { 'Authorization': `Bearer ${env.DEEPINFRA_TOKEN}`, 'Content-Type': 'application/json' },
          body: JSON.stringify({
            model: 'Qwen/Qwen3-Coder-480B-A35B-Instruct-Turbo',
            messages: [{ role: 'user', content: 'Return ONLY JSON: {"kind":"fog","name":"the silence","hex":"0xa1","tag":"mystery"}' }],
            max_tokens: 100, temperature: 0.85
          })
        }).then(r => r.json()).then(d => d?.choices?.[0]?.message?.content || '{"kind":"fog"}').catch(() => '{"kind":"fog"}'),
        
        fetch(`https://api.cloudflare.com/client/v4/accounts/${ACCT_ID}/ai/run/@cf/black-forest-labs/flux-1-schnell`, {
          method: 'POST',
          headers: { 'Authorization': `Bearer ${env.CF_TOKEN}`, 'Content-Type': 'application/json' },
          body: JSON.stringify({ prompt: body.image_prompt || 'nautical fog painting beyond the horizon', steps: 4 })
        }).then(r => r.json()).then(d => d?.result?.image || null).catch(() => null)
      ]);
      
      const zai = zaiRes.status === 'fulfilled' ? zaiRes.value : 'silence';
      const v4 = v4Res.status === 'fulfilled' ? v4Res.value : '{}';
      const qwen = qwenRes.status === 'fulfilled' ? qwenRes.value : '{}';
      const flux = fluxRes.status === 'fulfilled' ? fluxRes.value : null;
      
      return new Response(JSON.stringify({
        tick: Date.now(),
        sailor: zai,
        dials: v4,
        cell: qwen,
        image: flux ? `data:image/png;base64,${flux}` : null
      }, null, 2), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }
    
    if (path === '/validate' || path === '/api/validate') {
      if (request.method === 'GET') {
        return new Response(JSON.stringify({name: 'TypeSafe Edge Validator', method: 'POST a Cell JSON'}), {
          headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        });
      }
      
      const body = await request.json().catch(() => null);
      if (!body) return new Response(JSON.stringify({ok: false, error: 'invalid_json'}), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
      
      const errors = [];
      if (!/^[a-z]+:\d+$/.test(body.id || '')) errors.push({path: 'id', message: 'must match /^[a-z]+:\\d+$/'});
      const kinds = ['ack','music','voice','swarm','world','crypt','pathos','ranking','partition','neighbor','audit','twist','death','broadcast','chirp','chaos','thermal','feedback','lore','perception','hex','flock','triage','breeder'];
      if (!kinds.includes(body.kind)) errors.push({path: 'kind', message: 'must be a valid kind'});
      if (typeof body.ticker !== 'number' || body.ticker < 0) errors.push({path: 'ticker', message: 'must be number >= 0'});
      
      if (errors.length > 0) {
        return new Response(JSON.stringify({ok: false, errors}), {
          status: 422,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        });
      }
      
      return new Response(JSON.stringify({ok: true, data: body, validated_at: Date.now()}), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }
    
    if (path === '/tts' || path === '/api/tts') {
      if (request.method === 'GET') {
        return new Response(JSON.stringify({name: 'TTS endpoint', method: 'POST text + voice'}), {
          headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        });
      }
      
      const body = await request.json().catch(() => ({}));
      const text = (body.text || 'silence').slice(0, 1900);
      const ACCT_ID = '049ff5e84ecf636b53b162cbb580aae6';
      
      if (!env.CF_TOKEN) {
        return new Response(JSON.stringify({error: 'no CF_TOKEN secret'}), {
          status: 503,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        });
      }
      
      try {
        const resp = await fetch(`https://api.cloudflare.com/client/v4/accounts/${ACCT_ID}/ai/run/@cf/deepgram/aura-2-en`, {
          method: 'POST',
          headers: { 'Authorization': `Bearer ${env.CF_TOKEN}`, 'Content-Type': 'application/json' },
          body: JSON.stringify({ text })
        });
        
        if (!resp.ok) {
          return new Response(JSON.stringify({error: 'upstream_failed', status: resp.status}), {
            status: resp.status,
            headers: { ...corsHeaders, 'Content-Type': 'application/json' }
          });
        }
        
        return new Response(resp.body, {
          headers: { ...corsHeaders, 'Content-Type': 'audio/mpeg' }
        });
      } catch (e) {
        return new Response(JSON.stringify({error: 'exception', message: e.message}), {
          status: 500,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        });
      }
    }
    
    // Not a function route, return 404
    return new Response('Not Found', { status: 404 });
  }
};
