#!/usr/bin/env python3
"""SongForge Session 25 — ACE-Step local generation with Ollama-generated lyrics.

Generates indie folk covers of Casey's "Molding Memories" using:
1. ACE-Step 1.5 turbo on RTX 4050 (local, 6GB VRAM)
2. Lyrics generated by phi3 and qwen2.5 via Ollama
3. Original Casey lyrics for comparison

All tracks saved to /home/eileen/projects/covers/experiments_v5/
"""
import sys
import os

PROJECT_ROOT = "/home/eileen/projects/ACE-Step-1.5"
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

from acestep.handler import AceStepHandler
from acestep.llm_inference import LLMHandler
from acestep.inference import generate_music, GenerationParams, GenerationConfig

SAVE_DIR = "/home/eileen/projects/covers/experiments_v5"
os.makedirs(SAVE_DIR, exist_ok=True)

# Read lyrics files
def read_lyrics(name):
    path = f"/home/eileen/projects/ai-writings/music/{name}"
    with open(path) as f:
        return f.read()

# Original Casey lyrics
CASEY_LYRICS = read_lyrics("lyrics-molding-memories-clean.txt")
# Ollama-generated variants
PHI3_LYRICS = read_lyrics("lyrics-molding-memories-phi3.txt")
QWEN_LYRICS = read_lyrics("lyrics-molding-memories-qwen.txt")

TRACKS = [
    {
        "name": "s25-01-casey-original-warm-folk",
        "caption": "Warm indie folk, acoustic guitar fingerpicking, soft piano, intimate breathy male vocal, nostalgic and peaceful",
        "lyrics": CASEY_LYRICS,
        "duration": 45.0,
        "bpm": 85,
        "keyscale": "E major",
        "seed": 42,
    },
    {
        "name": "s25-02-qwen-indie-folk",
        "caption": "Gentle indie folk, fingerpicked acoustic guitar, light piano accents, warm male tenor, summer evening, bittersweet and hopeful",
        "lyrics": QWEN_LYRICS,
        "duration": 45.0,
        "bpm": 80,
        "keyscale": "E major",
        "seed": 100,
    },
    {
        "name": "s25-03-phi3-chamber-folk",
        "caption": "Chamber folk, cello and acoustic guitar, harpsichord accents, clear male vocal with harmony, autumnal and reflective",
        "lyrics": PHI3_LYRICS,
        "duration": 45.0,
        "bpm": 75,
        "keyscale": "A minor",
        "seed": 200,
    },
    {
        "name": "s25-04-casey-nashville-confession",
        "caption": "Nashville alt-country, resonator guitar, upright bass, brush snare, raw male vocal with slight rasp, confession booth intimacy",
        "lyrics": CASEY_LYRICS,
        "duration": 45.0,
        "bpm": 85,
        "keyscale": "E major",
        "seed": 300,
    },
    {
        "name": "s25-05-qwen-ambient-folk",
        "caption": "Ambient folk, electric guitar with reverb and delay, soft synth pads, whispered male vocal, dreamlike and ethereal",
        "lyrics": QWEN_LYRICS,
        "duration": 45.0,
        "bpm": 70,
        "keyscale": "C# minor",
        "seed": 400,
    },
    {
        "name": "s25-06-casey-blues-crossroads",
        "caption": "Delta blues folk, slide guitar, stomp box, raw anguished male vocal, humid and desperate",
        "lyrics": CASEY_LYRICS,
        "duration": 45.0,
        "bpm": 90,
        "keyscale": "E minor",
        "seed": 500,
    },
]

def main():
    print("=" * 60)
    print("SongForge Session 25 — ACE-Step Local Generation")
    print("=" * 60)

    # Initialize DiT handler (no LLM to save VRAM on 6GB card)
    print("\nInitializing ACE-Step DiT handler...")
    dit_handler = AceStepHandler()
    status, success = dit_handler.initialize_service(
        project_root=PROJECT_ROOT,
        config_path="acestep-v15-turbo",
        device="auto",
        use_flash_attention=False,
        compile_model=False,
        offload_to_cpu=True,
        offload_dit_to_cpu=True,
        quantization=None,
    )
    if not success:
        print(f"FAILED: {status}")
        sys.exit(1)
    print(f"DiT ready: {status}")

    llm_handler = LLMHandler()  # Empty handler, no LLM loaded

    config = GenerationConfig(
        batch_size=1,
        audio_format="mp3",
        mp3_bitrate="256k",
    )

    for i, track in enumerate(TRACKS):
        print(f"\n{'='*60}")
        print(f"Track {i+1}/{len(TRACKS)}: {track['name']}")
        print(f"{'='*60}")

        params = GenerationParams(
            task_type="text2music",
            caption=track["caption"],
            lyrics=track["lyrics"],
            duration=track["duration"],
            bpm=track["bpm"],
            keyscale=track["keyscale"],
            seed=track["seed"],
            guidance_scale=7.0,
            inference_steps=8,
            thinking=False,  # No LLM, so no thinking
            use_cot_metas=False,
            use_cot_caption=False,
            use_cot_lyrics=False,
            use_cot_language=False,
        )

        try:
            result = generate_music(
                dit_handler, llm_handler, params, config,
                save_dir=os.path.join(SAVE_DIR, track["name"]),
            )
            print(f"✅ Saved: {track['name']}")
        except Exception as e:
            print(f"❌ Failed: {e}")

    print("\n" + "=" * 60)
    print("Session 25 complete!")
    print(f"Output: {SAVE_DIR}")
    print("=" * 60)

if __name__ == "__main__":
    main()
