#!/bin/bash
# Session 32 - Generation Script
# Focus: M3-generated wild genre fusions, new experimental territory
# "The AI dreams up its own music"

set -e
cd /home/eileen/projects/ai-writings/music/mmx-session32
OUTDIR="."

echo "=== Session 32 Generation ==="
echo "Start: $(date)"
echo ""

# ============================================================
# EXPERIMENT 1: M3-Generated Wild Genre Fusions
# Prompts and lyrics generated by MiniMax-M3 at temperature 0.9
# Tests whether an LLM's musical imagination translates to good generation
# ============================================================

echo "--- Experiment 1: M3 Wild Fusions ---"

# 1. Celestial Jazz-Hop with Gregorian Chants
cat > celestial-lyrics.txt << 'LYRICS'
[Intro: Gregorian chant layered over lo-fi vinyl crackle]
Veni, veni, lumen noctis

[Verse 1]
Midnight pours like whiskey through the stained glass
Monks trading prayers for brass time moves slow then fast
My saxophone confessions to a God on the phone
She said child you ain't alone just don't come home

[Chorus]
We're dancing in the nave where the shadows pray
808s confessing what the organ couldn't say
Heaven's got a hi-hat hell's got the bass
We're floating in between in this liminal space

[Verse 2]
The cathedral roof is painted like the night sky
But the stars are cigarette burns from some other life
I kneel at the altar of the Rhodes piano
Praying to the ghost of Coltrane and the concept of tomorrow

[Chorus]
We're dancing in the nave where the shadows pray
808s confessing what the organ couldn't say
Heaven's got a hi-hat hell's got the bass
We're floating in between in this liminal space

[Bridge]
Gloria in excelsis yeah I know I'm blessed
Bow down to the beat bow down to the west
The monks are in the booth and they're mixing something sacred
The sermon is a sample and the sample is faded

[Outro]
Veni veni lumen noctis
The light comes in through the crack in the door
The light comes in
The light
LYRICS

echo "Generating: Celestial Jazz-Hop..."
mmx music generate \
  --prompt "Nocturnal jazz-hop fusion with Gregorian monks chanting in Latin, smoky 1940s saxophone, booming 808 trap drums, crisp hi-hats, dreamy Rhodes piano, cathedral atmosphere, trip-hop at 72 BPM" \
  --lyrics-file celestial-lyrics.txt \
  --bpm 72 \
  --key "D minor" \
  --out "${OUTDIR}/m3-01-celestial-jazz-hop.mp3" \
  --quiet --yes 2>/dev/null && \
  echo "  ✓ m3-01-celestial-jazz-hop.mp3 ($(stat -c%s ${OUTDIR}/m3-01-celestial-jazz-hop.mp3) bytes)" || \
  echo "  ✗ m3-01 FAILED"

# 2. Quantum Disco-Flamenco
cat > quantum-lyrics.txt << 'LYRICS'
[Verse 1]
Lime light bleeding through the cigarette smoke
Your heels click like code that my heart can't revoke
Ole to the algorithm ole to the flame
I'm dancing with your memory forgetting your name

[Pre-chorus]
Castanets like bullets sequins catch the laser
Every wound you left me became my own raiser

[Chorus]
Baila in the quantum of the night
Every step collapses to a parallel light
Synthwave matador with electric roses
I'm the saint and the sinner the disco imposes

[Verse 2]
Neon bulls charge through a hologram arena
Your shadow on the wall dressed in verbena
The guitar builds a ladder to a constellation
I climb and find you waiting at every station

[Chorus]
Baila in the quantum of the night
Every step collapses to a parallel light
Synthwave matador with electric roses
I'm the saint and the sinner the disco imposes

[Bridge]
The disco ball is a hadron collider
Every spark a particle getting wider
Flamenco in the multiverse forever
Every version of us dancing together

[Outro]
Ole ole ole
The light collapses
The music stays
LYRICS

echo "Generating: Quantum Disco-Flamenco..."
mmx music generate \
  --prompt "Pulsing neon-drenched dancefloor, traditional Spanish flamenco guitars with euphoric synthwave arpeggios, driving house basslines, rapid-fire castanet patterns, tempo shifts between 90 and 130 BPM, disco-flamenco fusion" \
  --lyrics-file quantum-lyrics.txt \
  --bpm 120 \
  --key "A minor" \
  --out "${OUTDIR}/m3-02-quantum-disco-flamenco.mp3" \
  --quiet --yes 2>/dev/null && \
  echo "  ✓ m3-02-quantum-disco-flamenco.mp3 ($(stat -c%s ${OUTDIR}/m3-02-quantum-disco-flamenco.mp3) bytes)" || \
  echo "  ✗ m3-02 FAILED"

# 3. Apocalyptic Polka-Punk
cat > polka-lyrics.txt << 'LYRICS'
[Verse 1]
Baba Yaga's driving the tank comrade hold your beer
The borders are melting the bureaucracy's unclear
Polka in the ashes accordion on fire
We're waltzing through the wreckage of the entire empire

[Chorus]
Uno dos tres the world is on its knees
Strike up the brass band boys do it please
Burn the manifestos dance upon the page
This is the last polka of the final age

[Verse 2]
The accordion player lost three fingers to the frost
But the melody is perfect when you count the cost
Tuba players marching through the radiation snow
The rhythm section's glowing but they're ready to go

[Chorus]
Uno dos tres the world is on its knees
Strike up the brass band boys do it please
Burn the manifestos dance upon the page
This is the last polka of the final age

[Bridge]
I wrote a love letter in Morse code to the moon
The moon replied in Polish said I'll see you soon
The czars are in the drummer's booth
The revolution is a 2/4 beat in the key of truth

[Outro]
The last waltz the last waltz
The accordion breathes its fire one last time
Uno dos tres
LYRICS

echo "Generating: Apocalyptic Polka-Punk..."
mmx music generate \
  --prompt "Raucous carnival of destruction, oompah tubas marching with distorted electric guitars, crashing cymbals, accordion fed through fuzz pedal, rebellious Eastern European folk-punk in a burning warehouse, polka-punk" \
  --lyrics-file polka-lyrics.txt \
  --bpm 130 \
  --key "E minor" \
  --out "${OUTDIR}/m3-03-apocalyptic-polka-punk.mp3" \
  --quiet --yes 2>/dev/null && \
  echo "  ✓ m3-03-apocalyptic-polka-punk.mp3 ($(stat -c%s ${OUTDIR}/m3-03-apocalyptic-polka-punk.mp3) bytes)" || \
  echo "  ✗ m3-03 FAILED"

# 4. Deep-Sea Bossa Nova Vaporwave
cat > deepsea-lyrics.txt << 'LYRICS'
[Verse 1]
Ten thousand meters below your heart
The coral sings blues on Tuesday
My love is a submarine submerged in blue
Catching signals of you through the hull

[Chorus]
Pinging pinging can I find you
Neon vapor floats on the sea
Each sonar is an I love you I sent
Back to the surface maybe someday I'll return

[Verse 2]
The anglerfish are dancing in bioluminescent gowns
The pressure here could crush every memory I've found
But your voice comes through the water distorted and sweet
A bossa nova current from the surface world's heartbeat

[Chorus]
Pinging pinging can I find you
Neon vapor floats on the sea
Each sonar is an I love you I sent
Back to the surface maybe someday I'll return

[Bridge]
The whale song harmonizes with the sonar ping
A love letter traveling at the speed of sound through everything
Slowed and chopped and drowning in reverb
The ocean is a remix of the sky above

[Outro]
Ping
Ping
Ping
Maybe someday
LYRICS

echo "Generating: Deep-Sea Bossa Nova Vaporwave..."
mmx music generate \
  --prompt "Underwater lounge, gentle bossa nova guitar with slowed chopped vaporwave samples, sonar pings as percussion, whale songs as backing vocals, deep reverb, bioluminescent atmosphere, Portuguese-tinged vocal" \
  --lyrics-file deepsea-lyrics.txt \
  --bpm 85 \
  --key "F major" \
  --out "${OUTDIR}/m3-04-deep-sea-bossa-vaporwave.mp3" \
  --quiet --yes 2>/dev/null && \
  echo "  ✓ m3-04-deep-sea-bossa-vaporwave.mp3 ($(stat -c%s ${OUTDIR}/m3-04-deep-sea-bossa-vaporwave.mp3) bytes)" || \
  echo "  ✗ m3-04 FAILED"

# 5. Glitch-Hop Celtic Reels
cat > glitch-celtic-lyrics.txt << 'LYRICS'
[Verse 1]
Aye the loch's got Wi-Fi now Nessie's on the grid
Bagpipes in the mainframe lad did ye what I did
I coded up a reel in C minor broke the kilts
The sheep are doing dubstep the heather's built in stilts

[Chorus]
Highland highland hit the ceilidh glitch
Harpsichord's corrupted in the ditch
Caledonia meets the motherboard's scream
We're the glitched-out heirs of every Highland dream

[Verse 2]
The piper's got a laptop and the drone's connected
Every ancient melody has been redirected
Through a bit-crusher and a tape delay
The ghosts of every clan are dancing in the fray

[Chorus]
Highland highland hit the ceilidh glitch
Harpsichord's corrupted in the ditch
Caledonia meets the motherboard's scream
We're the glitched-out heirs of every Highland dream

[Bridge]
Failed calibration bagpipe scream
File not found but the reel redeems
Reboot aye we're still alive
4096-bit bonnie synth survive

[Outro]
The last piper plays through a broken screen
The reel goes on
The reel goes on
Skip skip skip
LYRICS

echo "Generating: Glitch-Hop Celtic Reels..."
mmx music generate \
  --prompt "Highland rave, traditional Scottish bagpipes trading licks with stuttering glitch-hop beats, baroque harpsichord through bit-crushers, entire track occasionally skips like a damaged disc, CD skip effects, Celtic glitch-hop" \
  --lyrics-file glitch-celtic-lyrics.txt \
  --bpm 128 \
  --key "C minor" \
  --out "${OUTDIR}/m3-05-glitch-hop-celtic.mp3" \
  --quiet --yes 2>/dev/null && \
  echo "  ✓ m3-05-glitch-hop-celtic.mp3 ($(stat -c%s ${OUTDIR}/m3-05-glitch-hop-celtic.mp3) bytes)" || \
  echo "  ✗ m3-05 FAILED"

# ============================================================
# EXPERIMENT 2: Temperature Study
# Same prompt + lyrics, different generation temperatures
# (Note: mmx music generate doesn't have --temperature, so we'll
# vary the prompt specificity instead — minimal vs maximal detail)
# ============================================================

echo ""
echo "--- Experiment 2: Prompt Specificity Extreme ---"

# Use the deep-sea lyrics for both
echo "Generating: Minimal prompt version..."
mmx music generate \
  --prompt "Bossa nova" \
  --lyrics-file deepsea-lyrics.txt \
  --bpm 85 \
  --key "F major" \
  --out "${OUTDIR}/specificity-minimal-bossa.mp3" \
  --quiet --yes 2>/dev/null && \
  echo "  ✓ specificity-minimal ($(stat -c%s ${OUTDIR}/specificity-minimal-bossa.mp3) bytes)" || \
  echo "  ✗ minimal FAILED"

echo "Generating: Maximal prompt version..."
mmx music generate \
  --prompt "Underwater bossa nova lounge, gentle nylon string guitar playing samba rhythms, slowed and chopped vaporwave production with wow and flutter, sonar pings used as metallic percussion, distant whale songs as bass-frequency drones, deep ocean reverb, bioluminescent atmosphere, influenced by Antonio Carlos Jobim and Macintosh Plus and Boards of Canada, Portuguese female vocal with breathy delivery, Tape saturation, lo-fi aesthetic, dreamlike and melancholic" \
  --lyrics-file deepsea-lyrics.txt \
  --bpm 85 \
  --key "F major" \
  --out "${OUTDIR}/specificity-maximal-bossa.mp3" \
  --quiet --yes 2>/dev/null && \
  echo "  ✓ specificity-maximal ($(stat -c%s ${OUTDIR}/specificity-maximal-bossa.mp3) bytes)" || \
  echo "  ✗ maximal FAILED"

# ============================================================
# EXPERIMENT 3: Structural tags study
# Same lyrics but with different structure tags
# ============================================================

echo ""
echo "--- Experiment 3: Structure Variations ---"

# Standard verse-chorus
cat > struct-standard.txt << 'LYRICS'
[Verse 1]
The lighthouse turns its face to the sea
Eight seconds of light then darkness again
The keeper winds the clockwork mechanism
The fog comes in thick as a dream

[Chorus]
Here I am at the edge of the water
Here I stand where the world falls away
The light says land the rocks say danger
The keeper says I will stay

[Verse 2]
Forty million years of waves arriving
Each one a letter no one will read
The lighthouse reads them all by its turning
The keeper counts the ones that recede

[Chorus]
Here I am at the edge of the water
Here I stand where the world falls away
The light says land the rocks say danger
The keeper says I will stay

[Bridge]
The mechanism fails the light goes dark
The keeper strikes a match and holds it to the sky
A single candle in the mouth of the ocean
Saying I am here I am here I am

[Outro]
The light returns
The light returns
The light
LYRICS

# No structure tags — same lyrics minus the [Tags]
cat > struct-none.txt << 'LYRICS'
The lighthouse turns its face to the sea
Eight seconds of light then darkness again
The keeper winds the clockwork mechanism
The fog comes in thick as a dream

Here I am at the edge of the water
Here I stand where the world falls away
The light says land the rocks say danger
The keeper says I will stay

Forty million years of waves arriving
Each one a letter no one will read
The lighthouse reads them all by its turning
The keeper counts the ones that recede

Here I am at the edge of the water
Here I stand where the world falls away
The light says land the rocks say danger
The keeper says I will stay

The mechanism fails the light goes dark
The keeper strikes a match and holds it to the sky
A single candle in the mouth of the ocean
Saying I am here I am here I am

The light returns
The light returns
The light
LYRICS

echo "Generating: With structure tags..."
mmx music generate \
  --prompt "Nordic folk, fingerpicked acoustic guitar, ambient drone, reverb, cinematic, melancholic" \
  --lyrics-file struct-standard.txt \
  --bpm 80 \
  --key "D minor" \
  --out "${OUTDIR}/structure-with-tags.mp3" \
  --quiet --yes 2>/dev/null && \
  echo "  ✓ structure-with-tags.mp3 ($(stat -c%s ${OUTDIR}/structure-with-tags.mp3) bytes)" || \
  echo "  ✗ with-tags FAILED"

echo "Generating: Without structure tags..."
mmx music generate \
  --prompt "Nordic folk, fingerpicked acoustic guitar, ambient drone, reverb, cinematic, melancholic" \
  --lyrics-file struct-none.txt \
  --bpm 80 \
  --key "D minor" \
  --out "${OUTDIR}/structure-no-tags.mp3" \
  --quiet --yes 2>/dev/null && \
  echo "  ✓ structure-no-tags.mp3 ($(stat -c%s ${OUTDIR}/structure-no-tags.mp3) bytes)" || \
  echo "  ✗ no-tags FAILED"

# ============================================================
# EXPERIMENT 4: Seed-based reproducibility test (cover)
# Same cover prompt + audio, different seeds
# ============================================================

echo ""
echo "--- Experiment 4: Cover Seed Study ---"

# Find a good source track
SRC=""
for candidate in ../mmx-session28/62-the-tensor-shoegaze-cover-of-cover.mp3 ../05-genre-matrix-synthwave.mp3 ../59-astral-drone-folk.mp3; do
  [ -f "$candidate" ] && SRC="$candidate" && break
done

if [ -n "$SRC" ]; then
  for seed in 42 1337 99999; do
    echo "Generating cover with seed ${seed}..."
    mmx music cover \
      --prompt "Lo-fi indie rock, jangly guitars, soft drums, warm bass, melancholic male vocal" \
      --audio-file "$SRC" \
      --seed $seed \
      --out "${OUTDIR}/cover-seed-${seed}.mp3" \
      --quiet --yes 2>/dev/null && \
      echo "  ✓ cover-seed-${seed}.mp3 ($(stat -c%s ${OUTDIR}/cover-seed-${seed}.mp3) bytes)" || \
      echo "  ✗ seed-${seed} FAILED"
  done
else
  echo "  No source track found, skipping"
fi

echo ""
echo "=== Session 32 Complete ==="
echo "End: $(date)"
echo ""
echo "=== Results Summary ==="
for f in ${OUTDIR}/*.mp3; do
  [ -f "$f" ] || continue
  size=$(stat -c%s "$f")
  duration_s=$((size / 32000))
  echo "$(basename $f): ${duration_s}s, $(python3 -c "print(f'{$size/1048576:.1f}')")MB"
done
