#!/usr/bin/env python3
"""
Generate per-shelf index.html listing pages for the AI Writings Cloudflare Pages site.

The landing page (tools/generate-landing.py) links each shelf as href="<folder>/",
but only papers/ shipped an index.html — every other shelf 404'd and fell through
Cloudflare's SPA fallback to the root page. This script writes <folder>/index.html
for every folder in index.json (except 'root'), listing that shelf's entries
sorted by date descending, each linking to the file's actual path.

Style matches papers/index.html (Georgia serif, dark palette):
  bg #0a0a0f · surface #14141f · accent #44cc88 · links #8ab4f8

Safety: an existing <folder>/index.html is only overwritten if it carries this
script's marker comment (idempotent re-runs). Hand-made pages (papers/, site/,
radio-theater/, channel42/, the-tap/ …) are left untouched.

Usage:  python3 scripts/generate-shelves.py [--dry-run]
"""

import argparse
import html
import json
import sys
from collections import defaultdict
from pathlib import Path
from urllib.parse import quote

REPO_ROOT = Path(__file__).resolve().parent.parent
CATALOG = REPO_ROOT / "index.json"
MARKER = "<!-- shelf-index generated by scripts/generate-shelves.py -->"

STYLE = """body{background:#0a0a0f;color:#e8e0d0;font-family:Georgia,serif;max-width:760px;margin:0 auto;padding:40px 20px;line-height:1.6}
h1{color:#44cc88;font-weight:normal} a{color:#8ab4f8;text-decoration:none} a:hover{text-decoration:underline}
li{margin:7px 0;padding:7px 10px;background:#14141f;border:1px solid #22222f;border-radius:6px;list-style:none}
ul{padding:0} .sub{color:#999;font-style:italic;margin-bottom:30px}
.meta{color:#888;font-size:.8em;margin-left:8px;white-space:nowrap}
.back{font-size:0.85em;margin-top:40px} .back a{color:#44cc88}"""


def prettify(folder: str) -> str:
    return folder.replace("-", " ").replace("_", " ").strip().title() or folder


def render_shelf(folder: str, entries: list) -> str:
    entries = sorted(entries, key=lambda e: e.get("date") or "", reverse=True)
    items = []
    seen = set()
    for e in entries:
        path = e["path"]
        if path in seen:
            continue
        seen.add(path)
        title = html.escape(e.get("title") or e.get("filename") or path)
        date = e.get("date") or ""
        words = e.get("word_count") or 0
        meta = f'<span class="meta">{html.escape(date)} &middot; {words:,} words</span>'
        items.append(
            f'<li><a href="/{quote(path)}">{title}</a>{meta}</li>'
        )
    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{html.escape(prettify(folder))}</title>
{MARKER}
<style>
{STYLE}
</style></head><body>
<h1>{html.escape(prettify(folder))}</h1>
<p class="sub">{len(items)} entries &middot; shelf <code>{html.escape(folder)}</code></p>
<ul>
{chr(10).join(items)}
</ul>
<p class="back"><a href="/">&larr; Back to the library</a></p>
</body></html>
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true", help="report what would be written")
    args = ap.parse_args()

    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    shelves: dict[str, list] = defaultdict(list)
    for e in catalog:
        folder = e.get("folder")
        if not folder or folder == "root":
            continue
        shelves[folder].append(e)

    written, skipped_handmade, skipped_missing_dir = [], [], []
    for folder in sorted(shelves):
        out = REPO_ROOT / folder / "index.html"
        if out.exists() and MARKER not in out.read_text(encoding="utf-8", errors="replace"):
            skipped_handmade.append(folder)
            continue
        if not (REPO_ROOT / folder).is_dir() and not args.dry_run:
            (REPO_ROOT / folder).mkdir(parents=True, exist_ok=True)
        if not args.dry_run:
            page = render_shelf(folder, shelves[folder])
            out.write_text(page, encoding="utf-8")
        written.append(folder)

    print(f"Shelves in catalog (excluding root): {len(shelves)}")
    print(f"Generated: {len(written)} pages")
    for f in skipped_handmade:
        print(f"  preserved hand-made index.html: {f}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
